# Generated by Django 5.1.7 on 2025-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0006_customer_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.IntegerField(choices=[(1, 'File'), (2, 'Folder')], default=1),
        ),
    ]
