# Generated by Django 5.1.7 on 2025-04-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0007_posts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='starcast',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
