# Generated by Django 5.1.7 on 2025-04-10 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0008_posts_release_date_posts_starcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_parent_id', models.CharField(blank=True, max_length=255)),
                ('permission', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieplanet.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieplanet.role')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
