# Generated by Django 5.1.7 on 2025-04-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0009_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
