# Generated by Django 5.1.7 on 2025-04-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0010_posts_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='assign',
            field=models.TextField(blank=True, null=True),
        ),
    ]
