# Generated by Django 5.1.7 on 2025-04-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0011_roles_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='movieplanet.customer'),
        ),
    ]
