# Generated by Django 5.1.7 on 2025-04-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0012_alter_roles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='movieplanet.role'),
        ),
    ]
