# Generated by Django 5.1.7 on 2025-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0013_alter_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='parent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
