# Generated by Django 5.1.7 on 2025-04-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0014_posts_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='given',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given', to='movieplanet.customer'),
        ),
    ]
