# Generated by Django 5.1.7 on 2025-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0015_roles_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
