# Generated by Django 5.1.7 on 2025-04-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0016_alter_posts_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('parentId', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='0', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
