# Generated by Django 5.1.7 on 2025-04-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0017_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
