# Generated by Django 5.1.7 on 2025-04-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0019_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verify',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
