# Generated by Django 5.1.7 on 2025-04-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0020_customer_email_verify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
