# Generated by Django 5.1.7 on 2025-05-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0022_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
