# Generated by Django 5.1.7 on 2025-05-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0023_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('parentId', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='0', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='movieplanet.posts')),
            ],
        ),
    ]
