# Generated by Django 5.1.7 on 2025-05-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0024_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('to_address', models.EmailField(max_length=100)),
                ('from_address', models.EmailField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
