# Generated by Django 5.1.7 on 2025-05-31 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0025_mailmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
