# Generated by Django 5.1.7 on 2025-06-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0027_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, 'File'), (2, 'Folder')], default=1),
        ),
    ]
