# Generated by Django 5.1.7 on 2025-06-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0028_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
