# Generated by Django 5.1.7 on 2025-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0029_menu_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
