# Generated by Django 5.1.7 on 2025-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0030_posts_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
