# Generated by Django 5.1.7 on 2025-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0031_alter_posts_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='duration',
        ),
        migrations.AddField(
            model_name='posts',
            name='dur',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
