# Generated by Django 5.1.7 on 2025-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0032_remove_posts_duration_posts_dur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
