# Generated by Django 5.1.7 on 2025-06-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0033_alter_posts_dur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='dur',
            new_name='duration',
        ),
    ]
