# Generated by Django 5.1.7 on 2025-07-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0034_rename_dur_posts_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
