# Generated by Django 5.1.7 on 2025-07-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0035_alter_posts_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
