# Generated by Django 5.1.7 on 2025-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0036_alter_posts_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
