# Generated by Django 5.1.7 on 2025-07-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0037_alter_roles_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='created_at',
        ),
    ]
