# Generated by Django 5.1.7 on 2025-07-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0038_remove_roles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trand',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trands', to='movieplanet.posts'),
        ),
    ]
