# Generated by Django 5.1.7 on 2025-07-08 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieplanet', '0039_alter_trand_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='movieplanet.customer'),
        ),
    ]
