# Generated by Django 5.1.7 on 2025-04-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_role_user_roles_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.role'),
        ),
    ]
