# Generated by Django 5.1.7 on 2025-04-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_permission_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='roles',
            new_name='role',
        ),
    ]
